// micro-services-app-main/frontend-service/src/pages/Dashboard.jsx
import React from 'react';
import { Users, Package, Receipt, ArrowUpRight } from 'lucide-react';
import { Link } from 'react-router-dom';

const DashboardCard = ({ title, value, icon: Icon, color, to }) => (
    <Link to={to} className="card" style={{ display: 'block', textDecoration: 'none' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1rem' }}>
            <div style={{
                width: '48px',
                height: '48px',
                borderRadius: '12px',
                background: `rgba(${color}, 0.1)`,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: `rgb(${color})`
            }}>
                <Icon size={24} />
            </div>
            <ArrowUpRight size={20} color="var(--text-secondary)" />
        </div>
        <div style={{ fontSize: '2rem', fontWeight: '700', marginBottom: '0.25rem' }}>{value}</div>
        <div style={{ color: 'var(--text-secondary)', fontSize: '0.875rem' }}>{title}</div>
    </Link>
);

const Dashboard = () => {
    return (
        <div className="container">
            <h2 className="page-title">Dashboard Overview</h2>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '1.5rem', marginBottom: '3rem' }}>
                <DashboardCard
                    title="Total Customers"
                    value="Manage"
                    icon={Users}
                    color="99, 102, 241"
                    to="/customers"
                />
                <DashboardCard
                    title="Inventory Items"
                    value="Check"
                    icon={Package}
                    color="139, 92, 246"
                    to="/inventory"
                />
                <DashboardCard
                    title="Recent Bills"
                    value="View"
                    icon={Receipt}
                    color="16, 185, 129"
                    to="/billing"
                />
            </div>

            <div className="card">
                <h3 style={{ fontSize: '1.25rem', marginBottom: '1rem' }}>System Status</h3>
                <p style={{ color: 'var(--text-secondary)' }}>All microservices are running and communicating via Gateway Service (Port 8888).</p>
            </div>
        </div>
    );
};

export default Dashboard;

// micro-services-app-main/angular-service/src/app/pages/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-dashboard',
    standalone: true,
    imports: [RouterLink],
    templateUrl: './dashboard.component.html',
    styleUrl: './dashboard.component.css'
})
export class DashboardComponent { }

<div class="container fade-in">
    <h2 class="page-title">Dashboard Overview</h2>

    <div class="dashboard-grid">
        <a routerLink="/customers" class="card dashboard-card">
            <div class="card-header">
                <div class="icon-wrapper color-indigo">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                        <circle cx="9" cy="7" r="4" />
                        <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
                        <path d="M16 3.13a4 4 0 0 1 0 7.75" />
                    </svg>
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                    stroke="var(--text-secondary)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M7 7h10v10" />
                    <path d="M7 17 17 7" />
                </svg>
            </div>
            <div class="card-value">Manage</div>
            <div class="card-title">Total Customers</div>
        </a>

        <a routerLink="/inventory" class="card dashboard-card">
            <div class="card-header">
                <div class="icon-wrapper color-violet">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="m7.5 4.27 9 5.15" />
                        <path
                            d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
                        <path d="m3.3 7 8.7 5 8.7-5" />
                        <path d="M12 22v-9" />
                    </svg>
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                    stroke="var(--text-secondary)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M7 7h10v10" />
                    <path d="M7 17 17 7" />
                </svg>
            </div>
            <div class="card-value">Check</div>
            <div class="card-title">Inventory Items</div>
        </a>

        <a routerLink="/billing" class="card dashboard-card">
            <div class="card-header">
                <div class="icon-wrapper color-emerald">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z" />
                        <path d="M16 8h-6" />
                        <path d="M16 12h-6" />
                        <path d="M16 16h-6" />
                    </svg>
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                    stroke="var(--text-secondary)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M7 7h10v10" />
                    <path d="M7 17 17 7" />
                </svg>
            </div>
            <div class="card-value">View</div>
            <div class="card-title">Recent Bills</div>
        </a>
    </div>

    <div class="card">
        <h3 class="system-status-title">System Status</h3>
        <p class="system-status-text">All microservices are running and communicating via Gateway Service (Port 8888).
        </p>
    </div>
</div>
