// micro-services-app-main/frontend-service/src/pages/Customers.jsx
import React, { useEffect, useState } from 'react';
import api from '../api/axios';
import { Mail, User } from 'lucide-react';

const Customers = () => {
    const [customers, setCustomers] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchCustomers = async () => {
            try {
                const response = await api.get('/customer-service/api/customers');
                // Handle Spring Data REST structure
                const data = response.data._embedded ? response.data._embedded.customers : response.data;
                setCustomers(data);
            } catch (err) {
                console.error("Error fetching customers:", err);
                setError("Failed to load customers.");
            } finally {
                setLoading(false);
            }
        };

        fetchCustomers();
    }, []);

    if (loading) return <div className="container">Loading customers...</div>;
    if (error) return <div className="container" style={{ color: 'var(--danger)' }}>{error}</div>;

    return (
        <div className="container">
            <h2 className="page-title">Customers</h2>

            <div className="card table-container">
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                        </tr>
                    </thead>
                    <tbody>
                        {customers.map((customer) => (
                            <tr key={customer.id}>
                                <td style={{ width: '80px', color: 'var(--text-secondary)' }}>#{customer.id}</td>
                                <td>
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                                        <div style={{
                                            width: '32px',
                                            height: '32px',
                                            borderRadius: '50%',
                                            background: 'rgba(99, 102, 241, 0.1)',
                                            display: 'flex',
                                            alignItems: 'center',
                                            justifyContent: 'center',
                                            color: 'var(--accent-primary)'
                                        }}>
                                            <User size={16} />
                                        </div>
                                        <span style={{ fontWeight: 500 }}>{customer.name}</span>
                                    </div>
                                </td>
                                <td>
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--text-secondary)' }}>
                                        <Mail size={14} />
                                        {customer.email}
                                    </div>
                                </td>
                            </tr>
                        ))}
                        {customers.length === 0 && (
                            <tr>
                                <td colSpan="3" style={{ textAlign: 'center', padding: '2rem' }}>No customers found</td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default Customers;

// micro-services-app-main/angular-service/src/app/pages/customers/customers.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../../services/api.service';

@Component({
    selector: 'app-customers',
    standalone: true,
    imports: [CommonModule],
    templateUrl: './customers.component.html',
    styleUrl: './customers.component.css'
})
export class CustomersComponent implements OnInit {
    customers: any[] = [];
    loading = true;
    error: string | null = null;

    constructor(private api: ApiService) { }

    ngOnInit(): void {
        this.api.get('/customer-service/api/customers').subscribe({
            next: (data) => {
                this.customers = data._embedded ? data._embedded.customers : data;
                this.loading = false;
            },
            error: (err) => {
                console.error('Error fetching customers:', err);
                this.error = 'Failed to load customers.';
                this.loading = false;
            }
        });
    }
}

<div class="container fade-in">
    <h2 class="page-title">Customers</h2>

    <div *ngIf="loading" class="loading">Loading customers...</div>
    <div *ngIf="error" class="error">{{ error }}</div>

    <div *ngIf="!loading && !error" class="card table-container">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let customer of customers">
                    <td style="width: 80px; color: var(--text-secondary)">#{{ customer.id }}</td>
                    <td>
                        <div style="display: flex; align-items: center; gap: 0.75rem">
                            <div class="avatar">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round">
                                    <path d="M19 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                                    <circle cx="9" cy="7" r="4" />
                                </svg>
                            </div>
                            <span style="font-weight: 500">{{ customer.name }}</span>
                        </div>
                    </td>
                    <td>
                        <div style="display: flex; align-items: center; gap: 0.5rem; color: var(--text-secondary)">
                            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round">
                                <rect width="20" height="16" x="2" y="4" rx="2" />
                                <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
                            </svg>
                            {{ customer.email }}
                        </div>
                    </td>
                </tr>
                <tr *ngIf="customers.length === 0">
                    <td colspan="3" style="text-align: center; padding: 2rem">No customers found</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
