// micro-services-app-main/angular-service/src/app/pages/billing/billing.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../../services/api.service';

@Component({
    selector: 'app-billing',
    standalone: true,
    imports: [CommonModule],
    templateUrl: './billing.component.html',
    styleUrl: './billing.component.css'
})
export class BillingComponent implements OnInit {
    bills: any[] = [];
    loading = true;
    error: string | null = null;

    constructor(private api: ApiService) { }

    ngOnInit(): void {
        this.api.get('/billing-service/api/bills').subscribe({
            next: (data) => {
                this.bills = data._embedded ? data._embedded.bills : data;
                this.loading = false;
            },
            error: (err) => {
                console.error('Error fetching bills:', err);
                this.error = 'Failed to load bills.';
                this.loading = false;
            }
        });

    }
}

<div class="container fade-in">
    <h2 class="page-title">Billing</h2>

    <div *ngIf="loading" class="loading">Loading bills...</div>
    <div *ngIf="error" class="error">{{ error }}</div>

    <div *ngIf="!loading && !error" class="card table-container">
        <table>
            <thead>
                <tr>
                    <th>Bill ID</th>
                    <th>Date</th>
                    <th>Customer ID</th>
                    <th>Items Count</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let bill of bills">
                    <td style="width: 80px; color: var(--text-secondary)">#{{ bill.id }}</td>
                    <td>
                        <div style="display: flex; align-items: center; gap: 0.5rem">
                            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"
                                fill="none" stroke="var(--accent-secondary)" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round">
                                <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
                                <line x1="16" y1="2" x2="16" y2="6" />
                                <line x1="8" y1="2" x2="8" y2="6" />
                                <line x1="3" y1="10" x2="21" y2="10" />
                            </svg>
                            {{ bill.billingDate | date }}
                        </div>
                    </td>
                    <td>
                        <div style="display: flex; align-items: center; gap: 0.5rem">
                            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"
                                fill="none" stroke="var(--text-secondary)" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round">
                                <path d="M19 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                                <circle cx="9" cy="7" r="4" />
                            </svg>
                            {{ bill.customerId }}
                        </div>
                    </td>
                    <td>
                        <span class="badge badge-warning">
                            {{ bill.productItems ? bill.productItems.length : 'N/A' }} Items
                        </span>
                    </td>
                    <td>
                        <button class="btn action-btn">
                            View Details
                        </button>
                    </td>
                </tr>
                <tr *ngIf="bills.length === 0">
                    <td colspan="5" style="text-align: center; padding: 2rem">No bills found</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// micro-services-app-main/frontend-service/src/pages/Billing.jsx
import React, { useEffect, useState } from 'react';
import api from '../api/axios';
import { Receipt, Calendar, User } from 'lucide-react';

const Billing = () => {
    const [bills, setBills] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchBills = async () => {
            try {
                const response = await api.get('/billing-service/api/bills');
                const data = response.data._embedded ? response.data._embedded.bills : response.data;
                setBills(data);
            } catch (err) {
                console.error("Error fetching bills:", err);
                setError("Failed to load bills.");
            } finally {
                setLoading(false);
            }
        };

        fetchBills();
    }, []);

    if (loading) return <div className="container">Loading bills...</div>;
    if (error) return <div className="container" style={{ color: 'var(--danger)' }}>{error}</div>;

    return (
        <div className="container">
            <h2 className="page-title">Billing</h2>

            <div className="card table-container">
                <table>
                    <thead>
                        <tr>
                            <th>Bill ID</th>
                            <th>Date</th>
                            <th>Customer ID</th>
                            <th>Items Count</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {bills.map((bill) => (
                            <tr key={bill.id}>
                                <td style={{ width: '80px', color: 'var(--text-secondary)' }}>#{bill.id}</td>
                                <td>
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                        <Calendar size={14} color="var(--accent-secondary)" />
                                        {new Date(bill.billingDate).toLocaleDateString()}
                                    </div>
                                </td>
                                <td>
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                        <User size={14} color="var(--text-secondary)" />
                                        {bill.customerId}
                                    </div>
                                </td>
                                <td>
                                    <span className="badge badge-warning">
                                        {/* If productItems are not loaded in list view, handle gracefully */}
                                        {bill.productItems ? bill.productItems.length : 'N/A'} Items
                                    </span>
                                </td>
                                <td>
                                    <button className="btn" style={{ fontSize: '0.8rem', padding: '0.25rem 0.5rem', background: 'var(--bg-primary)', border: '1px solid var(--border-color)' }}>
                                        View Details
                                    </button>
                                </td>
                            </tr>
                        ))}
                        {bills.length === 0 && (
                            <tr>
                                <td colSpan="5" style={{ textAlign: 'center', padding: '2rem' }}>No bills found</td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default Billing;
