// micro-services-app-main/angular-service/src/app/pages/inventory/inventory.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../../services/api.service';

@Component({
    selector: 'app-inventory',
    standalone: true,
    imports: [CommonModule],
    templateUrl: './inventory.component.html',
    styleUrl: './inventory.component.css'
})
export class InventoryComponent implements OnInit {
    products: any[] = [];
    loading = true;
    error: string | null = null;

    constructor(private api: ApiService) { }

    ngOnInit(): void {
        this.api.get('/inventory-service/api/products').subscribe({
            next: (data) => {
                this.products = data._embedded ? data._embedded.products : data;
                this.loading = false;
            },
            error: (err) => {
                console.error('Error fetching inventory:', err);
                this.error = 'Failed to load inventory.';
                this.loading = false;
            }
        });
    }

    isLowStock(quantity: number): boolean {
        return quantity < 10;
    }
}

<div class="container fade-in">
    <h2 class="page-title">Inventory</h2>

    <div *ngIf="loading" class="loading">Loading inventory...</div>
    <div *ngIf="error" class="error">{{ error }}</div>

    <div *ngIf="!loading && !error" class="card table-container">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let product of products">
                    <td style="width: 80px; color: var(--text-secondary)">
                        <span [title]="product.id">{{ product.id | slice:0:8 }}...</span>
                    </td>
                    <td>
                        <div style="display: flex; align-items: center; gap: 0.75rem">
                            <div class="product-icon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round">
                                    <path d="m7.5 4.27 9 5.15" />
                                    <path
                                        d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
                                    <path d="m3.3 7 8.7 5 8.7-5" />
                                    <path d="M12 22v-9" />
                                </svg>
                            </div>
                            <span style="font-weight: 500">{{ product.name }}</span>
                        </div>
                    </td>
                    <td>
                        <div
                            style="display: flex; align-items: center; gap: 0.25rem; color: var(--success); font-weight: 600">
                            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round">
                                <line x1="12" y1="2" x2="12" y2="22" />
                                <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
                            </svg>
                            {{ product.price | number:'1.2-2' }}
                        </div>
                    </td>
                    <td>
                        <div style="display: flex; align-items: center; gap: 0.5rem">
                            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"
                                fill="none" stroke="var(--text-secondary)" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round">
                                <line x1="12" y1="20" x2="12" y2="10" />
                                <line x1="18" y1="20" x2="18" y2="4" />
                                <line x1="6" y1="20" x2="6" y2="16" />
                            </svg>
                            {{ product.quantity }}
                        </div>
                    </td>
                    <td>
                        <span class="badge" [ngClass]="isLowStock(product.quantity) ? 'badge-danger' : 'badge-success'">
                            {{ isLowStock(product.quantity) ? 'Low Stock' : 'In Stock' }}
                        </span>
                    </td>
                </tr>
                <tr *ngIf="products.length === 0">
                    <td colspan="5" style="text-align: center; padding: 2rem">No products found</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// micro-services-app-main/frontend-service/src/pages/Inventory.jsx
import React, { useEffect, useState } from 'react';
import api from '../api/axios';
import { Package, DollarSign, BarChart2 } from 'lucide-react';

const Inventory = () => {
    const [products, setProducts] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchProducts = async () => {
            try {
                const response = await api.get('/inventory-service/api/products');
                const data = response.data._embedded ? response.data._embedded.products : response.data;
                setProducts(data);
            } catch (err) {
                console.error("Error fetching inventory:", err);
                setError("Failed to load inventory.");
            } finally {
                setLoading(false);
            }
        };

        fetchProducts();
    }, []);

    if (loading) return <div className="container">Loading inventory...</div>;
    if (error) return <div className="container" style={{ color: 'var(--danger)' }}>{error}</div>;

    return (
        <div className="container">
            <h2 className="page-title">Inventory</h2>

            <div className="card table-container">
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Product Name</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {products.map((product) => {
                            const isLowStock = product.quantity < 10;
                            return (
                                <tr key={product.id}>
                                    <td style={{ width: '80px', color: 'var(--text-secondary)' }}>
                                        <span title={product.id}>{product.id.substring(0, 8)}...</span>
                                    </td>
                                    <td>
                                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                                            <div style={{
                                                width: '32px',
                                                height: '32px',
                                                borderRadius: '8px',
                                                background: 'rgba(139, 92, 246, 0.1)',
                                                display: 'flex',
                                                alignItems: 'center',
                                                justifyContent: 'center',
                                                color: 'var(--accent-secondary)'
                                            }}>
                                                <Package size={16} />
                                            </div>
                                            <span style={{ fontWeight: 500 }}>{product.name}</span>
                                        </div>
                                    </td>
                                    <td>
                                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem', color: 'var(--success)', fontWeight: 600 }}>
                                            <DollarSign size={14} />
                                            {product.price.toFixed(2)}
                                        </div>
                                    </td>
                                    <td>
                                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                            <BarChart2 size={14} color="var(--text-secondary)" />
                                            {product.quantity}
                                        </div>
                                    </td>
                                    <td>
                                        <span className={`badge ${isLowStock ? 'badge-danger' : 'badge-success'}`}>
                                            {isLowStock ? 'Low Stock' : 'In Stock'}
                                        </span>
                                    </td>
                                </tr>
                            );
                        })}
                        {products.length === 0 && (
                            <tr>
                                <td colSpan="5" style={{ textAlign: 'center', padding: '2rem' }}>No products found</td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default Inventory;
